# Assignment-3
## UCS420 "Cognitive Computing"
## Pandas

## Q.1 Create a dataset as follow in the table.

In [2]:
import pandas as pd
import numpy as np

data = {
    'Tid': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Refund': ['Yes', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No'],
    'Marital Status': ['Single', 'Married', 'Single', 'Married', 'Divorced',
                        'Married', 'Divorced', 'Single', 'Married', 'Single'],
    'Taxable Income': ['125K', '100K', '70K', '120K', '95K',
                        '60K', '220K', '85K', '75K', '90K'],
    'Cheat': ['No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Q.2 Locate row 0, 4, 7 and 8 using DataFrame.

In [3]:
df.loc[[0, 4, 7, 8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Q.3 Navigate the DataFrame

### 1. Select row from index 3 to 7.

In [4]:
df.loc[3:7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

### 2. Select row from index 4 to 8, and column 2 to 4.

In [5]:
df.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

### 3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [6]:
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Q.4 Read a csv file and display its first five rows.
Dataset downloaded from https://www.kaggle.com/datasets/uciml/iris and unzipped to get `Iris.csv`.

In [7]:
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## Q.5 From the csv file (uploaded in Q.4) delete row 4, and delete column 3. Display the result.

In [8]:
iris_modified = iris.drop(index=4)
iris_modified = iris_modified.drop(iris_modified.columns[3], axis=1)
iris_modified.head(10)

    Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0    1            5.1           3.5           0.2  Iris-setosa
1    2            4.9           3.0           0.2  Iris-setosa
2    3            4.7           3.2           0.2  Iris-setosa
3    4            4.6           3.1           0.2  Iris-setosa
5    6            5.4           3.9           0.4  Iris-setosa
6    7            4.6           3.4           0.3  Iris-setosa
7    8            5.0           3.4           0.2  Iris-setosa
8    9            4.4           2.9           0.2  Iris-setosa
9   10            4.9           3.1           0.1  Iris-setosa
10  11            5.4           3.7           0.2  Iris-setosa

## Q.6 Create a sample dataset (employees.csv) containing information about employees in a company.

In [9]:
employee_data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Edward'],
    'Department': ['HR', 'IT', 'IT', 'Marketing', 'Sales'],
    'Age': [29, 34, 41, 28, 38],
    'Salary': [50000, 70000, 65000, 55000, 60000],
    'Years_of_Experience': [4, 8, 10, 3, 12],
    'Joining_Date': ['2020-03-15', '2017-07-19', '2013-06-01', '2021-02-10', '2010-11-25'],
    'Gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'Bonus': [5000, 7000, 6000, 4500, 5000],
    'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
}

emp_df = pd.DataFrame(employee_data)
emp_df.to_csv('employees.csv', index=False)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [13]:
emp_df = pd.read_csv('employees.csv')
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### a) Shape (number of rows and columns) of the DataFrame.

In [14]:
emp_df.shape

(5, 10)

### b) Summary of the DataFrame that includes the data types and non-null counts for each column.

In [15]:
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 528.0+ bytes

### c) Generate descriptive statistics.

In [16]:
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

### d) Display the first 5 rows and last 3 rows of the dataset.

In [17]:
print("First 5 rows:")
display(emp_df.head(5))

print("\nLast 3 rows:")
display(emp_df.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

### e) Calculate the following statistics from the dataset:
i. The average salary of employees.
ii. The total bonus paid to all employees.
iii. The youngest employee's age.
iv. The highest performance rating.

In [18]:
avg_salary = emp_df['Salary'].mean()
total_bonus = emp_df['Bonus'].sum()
youngest_age = emp_df['Age'].min()
highest_rating = emp_df['Rating'].max()

print(f"i. Average salary of employees: {avg_salary}")
print(f"ii. Total bonus paid to all employees: {total_bonus}")
print(f"iii. Youngest employee's age: {youngest_age}")
print(f"iv. Highest performance rating: {highest_rating}")

i. Average salary of employees: 60000.0
ii. Total bonus paid to all employees: 27500
iii. Youngest employee's age: 28
iv. Highest performance rating: 4.7

### f) Sort the DataFrame by the Salary column in descending order.

In [19]:
emp_df_sorted = emp_df.sort_values(by='Salary', ascending=False)
emp_df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

### g) Add a new column that categorizes employees based on their performance rating:
i. Excellent for ratings >= 4.5
ii. Good for ratings >= 4.0 but < 4.5
iii. Average for ratings < 4.0

In [20]:
def categorize_rating(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'

emp_df['Performance_Category'] = emp_df['Rating'].apply(categorize_rating)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### h) Identify missing values in the DataFrame.

In [21]:
emp_df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

### i) Rename the Employee_ID column to ID.

In [22]:
emp_df.rename(columns={'Employee_ID': 'ID'}, inplace=True)
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

### j) Find all employees who:
i. Have more than 5 years of experience.
ii. Belong to the IT department.

In [23]:
more_than_5_years = emp_df[emp_df['Years_of_Experience'] > 5]
print("Employees with more than 5 years of experience:")
display(more_than_5_years)

Employees with more than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [24]:
it_department = emp_df[emp_df['Department'] == 'IT']
print("Employees belonging to the IT department:")
display(it_department)

Employees belonging to the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

### k) Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary.

In [25]:
emp_df['Tax'] = emp_df['Salary'] * 0.10
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

### l) Save the modified DataFrame (with added columns) to a new CSV file.

In [26]:
emp_df.to_csv('employees_modified.csv', index=False)
print("Modified DataFrame saved to 'employees_modified.csv'")

Modified DataFrame saved to 'employees_modified.csv'